#!/bin/bash
# ======================================================================
# entrypoint.sh — Claude Code dev environment bootstrap
#
# Runs as the container's ENTRYPOINT. Receives configuration via env
# vars from the launcher (claude-dev.sh on the host):
#   GH_OWNER, GH_REPO            project identity
#   GH_TOKEN                     GitHub Token (read/write per scoping)
#   CLAUDE_CODE_OAUTH_TOKEN      consumed later by claude itself
#   TZ                           host timezone
#   ISSUE_ID                     optional GitHub Issue number
#   CLAUDE_DEV_PROXY_SOCKET      path to bind-mounted proxy socket
#   CLAUDE_DEV_PROXY_PORT        local port to expose the proxy via socat bridge
#
# Organized into two logical sections:
#   1. BASE — generic Claude Code dev environment bootstrap
#   2. PROJECT — molim-specific dependency installation
#
# Eventually the BASE section will be extracted into a separately-
# published base image's entrypoint; for now both live here.
#
# ======================================================================

set -euo pipefail

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------
section() {
    printf '\n\033[1;32m==> %s\033[0m\n' "$*"
}

die() {
    printf '\033[1;31mError:\033[0m %s\n' "$*" >&2
    exit 1
}

warning() {
    printf '\033[1;33mWarning:\033[0m %s\n' "$*" >&2
}

success() {
    printf '\033[1;32m✓\033[0m %s\n' "$*"
}

# ======================================================================
# BASE — generic Claude Code dev environment bootstrap
# ======================================================================
section "Welcome to ephemeral Claude Code dev environment"

# ----------------------------------------------------------------------
# Validate required environment
# ----------------------------------------------------------------------
section "Validating environment"

bootstrap_failure() {
    printf '\n\033[1;31m==> %s\033[0m\n' "Entrypoint bootstrap failed, Claude container cannot proceed."
    read -r -s -n 1 -p $'\nPress any key to exit the container...' _
}
trap bootstrap_failure EXIT

require_env() {
    local var="$1"
    local show_value="${2:-false}"
    if [[ -z "${!var:-}" ]]; then
        die "required environment variable '${var}' is not set; check the launcher."
    fi
    local text="$var"
    if [[ "$show_value" == "true" ]]; then
        text="${text}=${!var}"
    fi
    success "$text"
}

require_env GH_OWNER true
require_env GH_REPO true
require_env GH_TOKEN
require_env CLAUDE_CODE_OAUTH_TOKEN
require_env TZ true
require_env CLAUDE_DEV_PROXY_SOCKET
require_env CLAUDE_DEV_PROXY_PORT
require_env CLAUDE_CODE_VERSION true

# ----------------------------------------------------------------------
# Issue ID handling
# ----------------------------------------------------------------------
if [[ -n "${ISSUE_ID:-}" ]]; then
    success "ISSUE_ID=${ISSUE_ID}"
else
    success "ISSUE_ID not set. No specific Issue context."
fi

# ----------------------------------------------------------------------
# Shell prompt configuration
# ----------------------------------------------------------------------
section "Configuring shell prompt"

configure_prompt() {
    local context="${GH_REPO}"

    if [[ -n "${ISSUE_ID:-}" ]]; then
        context="${context} #${ISSUE_ID}"
    fi

    # This is an ephemeral container; overwriting .bashrc is intentional.
    cat > "${HOME}/.bashrc" <<EOF
# Claude dev container prompt.
# Generated by entrypoint.sh.

export PS1='\\[\\033[1;36m\\][claude-dev ${context}]\\[\\033[0m\\] \\w\\$ '
EOF
}
configure_prompt
success "Shell prompt configured."

# ----------------------------------------------------------------------
# Verify /workspace exists, is accessible and empty
# A non-empty /workspace means the container deviates from design
# (a bind mount, a stale tmpfs, etc.); fail loudly rather than risk
# clobbering or merging unexpected content.
# ----------------------------------------------------------------------
section "Verifying /workspace initial state"

[[ -d /workspace ]] || die "/workspace does not exist."
[[ -r /workspace && -x /workspace ]] || die "/workspace is not accessible."
[[ -n "$(ls -A /workspace 2>/dev/null)" ]] && die "/workspace is not empty."
success "/workspace is ready."

# ----------------------------------------------------------------------
# Check container network mode - expected --network none
# No routes, only loopback interface.
# Show warning if this does not appear to be the case, but do not fail.
# ----------------------------------------------------------------------
section "Checking container network"

verify_network_mode() {
    local interfaces=""
    local has_non_loopback=0
    local has_default_route=0

    # /sys/class/net is available without iproute2/net-tools.
    if [[ -d /sys/class/net ]]; then
        interfaces="$(basename -a /sys/class/net/* 2>/dev/null | sort | tr '\n' ' ')"

        while IFS= read -r iface; do
            if [[ "$iface" != "lo" ]]; then
                has_non_loopback=1
                break
            fi
        done < <(basename -a /sys/class/net/* 2>/dev/null)
    else
        warning "Cannot inspect /sys/class/net; unable to verify container network mode."
        return 0
    fi

    # /proc/net/route exposes kernel route table without requiring iproute2.
    # A default route has destination 00000000.
    if [[ -r /proc/net/route ]]; then
        if awk 'NR > 1 && $2 == "00000000" { found=1 } END { exit found ? 0 : 1 }' /proc/net/route; then
            has_default_route=1
        fi
    else
        warning "Cannot inspect /proc/net/route; unable to verify default route state."
    fi

    if [[ "$has_non_loopback" -eq 1 || "$has_default_route" -eq 1 ]]; then
        warning "Container does not appear to be running with Docker --network none."
        warning "Detected network interfaces: ${interfaces:-unknown}"
        if [[ "$has_default_route" -eq 1 ]]; then
            warning "Detected a default route in /proc/net/route."
        fi
        warning "Network isolation is expected to be enforced by the host launcher."
    else
        success "Network mode: loopback-only."
    fi
}
verify_network_mode

# ----------------------------------------------------------------------
# Check container capability and privilege restrictions
# Expected: all capabilities dropped, no-new-privileges enabled.
# Show warning if this does not appear to be the case, but do not fail.
# ----------------------------------------------------------------------
section "Checking container capability and privilege restrictions"

verify_capability_hardening() {
    local cap_eff=""
    local no_new_privs=""

    if [[ ! -r /proc/self/status ]]; then
        warning "Cannot inspect /proc/self/status; unable to verify capability/no-new-privileges state."
        return 0
    fi

    cap_eff="$(awk '/^CapEff:/ {print $2}' /proc/self/status)"
    no_new_privs="$(awk '/^NoNewPrivs:/ {print $2}' /proc/self/status)"

    if [[ "$cap_eff" == "0000000000000000" ]]; then
        success "Capabilities: none effective."
    else
        warning "Container effective capabilities are not fully dropped: CapEff=${cap_eff:-unknown}"
    fi

    if [[ "$no_new_privs" == "1" ]]; then
        success "Privileges: no-new-privileges enabled."
    else
        warning "Container no-new-privileges is not enabled: NoNewPrivs=${no_new_privs:-unknown}"
    fi
}
verify_capability_hardening

# ----------------------------------------------------------------------
# Check container root filesystem is read-only
# Expected: read-only root with writable tmpfs mounts as needed.
# Show warning if root is not read-only, but do not fail.
# ----------------------------------------------------------------------

section "Checking container filesystem"

mount_field() {
    local path="$1"
    local field="$2"

    awk -v path="$path" -v field="$field" '
        $2 == path { value = $field }
        END {
            if (value != "") {
                print value
            } else {
                exit 1
            }
        }
    ' /proc/mounts
}

mount_fstype() {
    mount_field "$1" 3
}

mount_options() {
    mount_field "$1" 4
}

mount_has_option() {
    local path="$1"
    local option="$2"
    local options

    if ! options="$(mount_options "$path" 2>/dev/null)"; then
        return 1
    fi

    [[ ",${options}," == *",${option},"* ]]
}

check_mount_is_tmpfs() {
    local path="$1"
    local fstype

    if ! fstype="$(mount_fstype "$path" 2>/dev/null)"; then
        warning "Expected mount not found: ${path}"
        return 1
    fi

    if [[ "$fstype" != "tmpfs" ]]; then
        warning "Expected ${path} to be tmpfs, got filesystem type: ${fstype}"
        return 1
    fi

    return 0
}

check_path_writable() {
    local path="$1"
    local test_file="${path%/}/.claude-dev-write-check.$$"

    if ( : > "$test_file" ) 2>/dev/null; then
        rm -f "$test_file" 2>/dev/null || true
        return 0
    fi

    warning "Expected path to be writable by current user, but write failed: ${path}"
    return 1
}

check_path_owner() {
    local path="$1"
    local expected_uid="$2"
    local expected_gid="$3"
    local actual

    if ! actual="$(stat -c '%u:%g' "$path" 2>/dev/null)"; then
        warning "Cannot stat expected writable path: ${path}"
        return 1
    fi

    if [[ "$actual" != "${expected_uid}:${expected_gid}" ]]; then
        warning "Unexpected ownership for ${path}: got ${actual}, expected ${expected_uid}:${expected_gid}"
        return 1
    fi

    return 0
}

verify_filesystem_hardening() {
    local failed=0
    local uid gid
    local expected_tmpfs_paths

    uid="$(id -u)"
    gid="$(id -g)"

    expected_tmpfs_paths=(
        "$HOME"
        "/workspace"
        "/tmp"
        "/var/tmp"
        "/run"
    )

    # Root filesystem is mounted read-only.
    if mount_has_option "/" "ro"; then
        success "Root filesystem is mounted read-only."
    else
        warning "Root filesystem does not appear to be mounted read-only."
        failed=1
    fi

    # Expected writable tmpfs mounts exist.
    local tmpfs_ok=1
    for path in "${expected_tmpfs_paths[@]}"; do
        if ! check_mount_is_tmpfs "$path"; then
            tmpfs_ok=0
            failed=1
        fi
    done

    if [[ "$tmpfs_ok" -eq 1 ]]; then
        success "Expected writable paths are tmpfs mounts."
    fi

    # Writable tmpfs mounts are writable by the current user.
    local writable_ok=1
    for path in "${expected_tmpfs_paths[@]}"; do
        if ! check_path_writable "$path"; then
            writable_ok=0
            failed=1
        fi
    done

    if [[ "$writable_ok" -eq 1 ]]; then
        success "Expected tmpfs mounts are writable by current user."
    fi

    # Root filesystem rejects writes outside approved writable mounts.
    #
    # This is a practical smoke test. Failure to write is expected. The
    # earlier mount-option check is the stronger verification that / is ro.
    local root_write_failed=1

    if (: > "/.claude-dev-rootfs-write-check.$$") 2>/dev/null; then
        warning "Unexpectedly wrote to root filesystem path: /.claude-dev-rootfs-write-check.$$"
        rm -f "/.claude-dev-rootfs-write-check.$$" 2>/dev/null || true
        root_write_failed=0
        failed=1
    fi

    if (: > "/etc/.claude-dev-rootfs-write-check.$$") 2>/dev/null; then
        warning "Unexpectedly wrote to root filesystem path: /etc/.claude-dev-rootfs-write-check.$$"
        rm -f "/etc/.claude-dev-rootfs-write-check.$$" 2>/dev/null || true
        root_write_failed=0
        failed=1
    fi

    if [[ "$root_write_failed" -eq 1 ]]; then
        success "Writes outside approved writable mounts are rejected."
    fi

    # Expected tmpfs mount ownership matches runtime user.
    local ownership_ok=1
    for path in "${expected_tmpfs_paths[@]}"; do
        if ! check_path_owner "$path" "$uid" "$gid"; then
            ownership_ok=0
            failed=1
        fi
    done

    if [[ "$ownership_ok" -eq 1 ]]; then
        success "Expected tmpfs mounts are owned by current user (${uid}:${gid})."
    fi

    # Executable paths are executable where needed.
    local exec_ok=1

    if mount_has_option "$HOME" "noexec"; then
        warning "${HOME} is mounted noexec, but uv/Claude tooling may need to execute files from it."
        exec_ok=0
        failed=1
    fi

    if mount_has_option "/workspace" "noexec"; then
        warning "/workspace is mounted noexec, but project tooling may need to execute files from it."
        exec_ok=0
        failed=1
    fi

    if [[ "$exec_ok" -eq 1 ]]; then
        success "Executable tmpfs paths are not mounted noexec."
    fi

    # Runtime path /run is mounted noexec.
    if mount_has_option "/run" "noexec"; then
        success "/run is mounted noexec."
    else
        warning "/run is not mounted noexec."
        failed=1
    fi

    # No unexpected non-tmpfs writable mountpoints.
    #
    # Ignore expected Docker/pseudo filesystems and Docker-managed config
    # file mounts. Warn on unexpected writable non-tmpfs mounts.
    local unexpected_mounts=""
    while read -r source target fstype options rest; do
        [[ ",${options}," == *",rw,"* ]] || continue

        case "$fstype" in
            tmpfs|proc|sysfs|devpts|mqueue|cgroup|cgroup2|devtmpfs)
                continue
                ;;
        esac

        case "$target" in
            /etc/hosts|/etc/hostname|/etc/resolv.conf)
                continue
                ;;
        esac

        unexpected_mounts+="${target} (${fstype}, ${options})"$'\n'
    done < /proc/mounts

    if [[ -n "$unexpected_mounts" ]]; then
        warning "Unexpected writable non-tmpfs mountpoints detected:"
        printf '%s' "$unexpected_mounts" | sed 's/^/  - /' >&2
        failed=1
    else
        success "No unexpected writable non-tmpfs mountpoints detected."
    fi

    if [[ "$failed" -eq 0 ]]; then
        success "Read-only root and tmpfs hardening checks passed."
    fi
}
verify_filesystem_hardening

# ----------------------------------------------------------------------
# Local proxy configuration
# The real Envoy proxy is exposed on a bind-mounted socket at $CLAUDE_DEV_PROXY_SOCKET.
# socat is used as a bridge to connect to the proxy.
# ----------------------------------------------------------------------
section "Network proxy bridge initialization"

start_proxy_bridge() {
    local socket_path="${CLAUDE_DEV_PROXY_SOCKET}"
    local proxy_port="${CLAUDE_DEV_PROXY_PORT:-8080}"
    local proxy_url="http://127.0.0.1:${proxy_port}"
    local log_file="/tmp/claude-dev-proxy-socat.log"

    if [[ ! -S "${socket_path}" ]]; then
        die "proxy socket not found or not a socket: ${socket_path}"
    fi

    : > "${log_file}"

    socat -d -d \
        "TCP-LISTEN:${proxy_port},bind=127.0.0.1,reuseaddr,fork" \
        "UNIX-CONNECT:${socket_path}" \
        2>"${log_file}" &

    local socat_pid="$!"

    # Wait until the local TCP listener is reachable.
    for _ in {1..50}; do
        if ! kill -0 "${socat_pid}" >/dev/null 2>&1; then
            cat "${log_file}" >&2 || true
            die "network proxy bridge process exited before becoming ready."
        fi

        if timeout 1 bash -c ":</dev/tcp/127.0.0.1/${proxy_port}" >/dev/null 2>&1; then
            export HTTP_PROXY="${proxy_url}"
            export HTTPS_PROXY="${proxy_url}"
            export http_proxy="${proxy_url}"
            export https_proxy="${proxy_url}"
            export NO_PROXY="${NO_PROXY:-localhost,127.0.0.1,::1}"
            export no_proxy="${no_proxy:-localhost,127.0.0.1,::1}"

            echo "Proxy socket: ${socket_path}"
            echo "Proxy bridge: ${proxy_url}"
            echo "socat log: ${log_file}"
            success "Network proxy bridge started."
            return 0
        fi

        sleep 0.1
    done

    cat "${log_file}" >&2 || true
    die "network proxy bridge did not become ready on 127.0.0.1:${proxy_port}"
}
start_proxy_bridge

# ----------------------------------------------------------------------
# Configure GitHub authentication via gh
# This installs gh's git credential helper as a side effect, so both
# `gh` and `git` work against github.com without further setup.
# ----------------------------------------------------------------------
section "Configuring GitHub authentication"

GH_TOKEN_TMP="$GH_TOKEN"
# gh auth is not working properly with GH_TOKEN env var present, so need to move it to a temp var and unset.
unset GH_TOKEN
echo "$GH_TOKEN_TMP" | gh auth login --with-token --hostname github.com
# After gh authentication, the token is stored in gh's credential helper config and the GH_TOKEN/GH_TOKEN_TMP env var is no longer needed.
unset GH_TOKEN_TMP
gh auth setup-git
gh auth status
success "GitHub authentication initialized."

# ----------------------------------------------------------------------
# Configure git identity
# Author is "Claude Code (authorized by <gh-user>)", email uses GitHub's
# noreply format keyed by the human's numeric user ID so the avatar
# routes to the human's profile.
# ----------------------------------------------------------------------
section "Configuring git identity"

GH_USER_ID="$(gh api user --jq .id)"
GH_USERNAME="$(gh api user --jq .login)"
GIT_AUTHOR_NAME="Claude Code (authorized by ${GH_USERNAME})"
GIT_AUTHOR_EMAIL="${GH_USER_ID}+${GH_USERNAME}@users.noreply.github.com"
git config --global user.name  "${GIT_AUTHOR_NAME}"
git config --global user.email "${GIT_AUTHOR_EMAIL}"
success "Author: ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>."

# ----------------------------------------------------------------------
# Clone the project repository
# ----------------------------------------------------------------------
section "Cloning ${GH_OWNER}/${GH_REPO} into /workspace"

git clone "https://github.com/${GH_OWNER}/${GH_REPO}.git" /workspace
cd /workspace
success "Repository cloned."

# ----------------------------------------------------------------------
# Resolve and check out the working branch
#
#   ISSUE_ID not set                       -> stay on main
#   ISSUE_ID set, issue does not exist     -> error
#   ISSUE_ID set, issue exists, 0 branches -> stay on main
#   ISSUE_ID set, issue exists, 1 branch   -> check it out
#   ISSUE_ID set, issue exists, ≥2 branches -> refuse and exit
#
# Implemented via GraphQL because `gh issue develop --list` does not
# support --json output. The first:2 cap is sufficient since logic
# only distinguishes 0 / 1 / multiple.
# ----------------------------------------------------------------------
section "Resolving working branch"

resolve_working_branch() {
    if [[ -z "${ISSUE_ID:-}" ]]; then
        success "No ISSUE_ID; staying on main."
    else

        if ! gh issue view "${ISSUE_ID}" --repo "${GH_OWNER}/${GH_REPO}" --json number >/dev/null 2>&1; then
            die "issue #${ISSUE_ID} not found in ${GH_OWNER}/${GH_REPO}."
        fi

        local query_result="$(gh api graphql \
            -F owner="${GH_OWNER}" \
            -F repo="${GH_REPO}" \
            -F number="${ISSUE_ID}" \
            -f query='
                query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                    issue(number: $number) {
                    linkedBranches(first: 2) {
                        nodes { ref { name } }
                    }
                    }
                }
                }')"

        # Issue not found -> .data.repository.issue is null
        if [[ "$(echo "${query_result}" | jq '.data.repository.issue')" == "null" ]]; then
            die "issue #${ISSUE_ID} not returned by GraphQL API in ${GH_OWNER}/${GH_REPO}."
        fi

        local linked_branches="$(echo "${query_result}" | jq -r '.data.repository.issue.linkedBranches.nodes | map(.ref.name)')"
        local linked_count="$(echo "${linked_branches}" | jq 'length')"

        case "${linked_count}" in
            0)
                success "Issue #${ISSUE_ID}: no linked branch yet; staying on main."
                echo "Branch creation is the SDLC's spec phase responsibility."
                ;;
            1)
                local branch="$(echo "${linked_branches}" | jq -r '.[0]')"
                echo "Issue #${ISSUE_ID}: one linked branch (${branch}); checking out."
                git checkout "${branch}"
                success "Checked out linked branch ${branch} for Issue #${ISSUE_ID}."
                ;;
            *)
                echo "Issue #${ISSUE_ID}: multiple linked branches found:" >&2
                echo "${linked_branches}" | jq -r '.[]' | sed 's/^/  - /' >&2
                die "ambiguous branch state. Resolve in GitHub (Issue page → Development sidebar → unlink unwanted branches) and retry."
                ;;
        esac
    fi
}
resolve_working_branch

# ----------------------------------------------------------------------
# Write ~/.claude.json
# Suppresses the first-run onboarding wizard (theme picker, login method
# screen). hasCompletedOnboarding is the gate; lastOnboardingVersion
# must match the installed Claude Code version. Template lives at
# /etc/claude-dev/.claude.json.template (baked into the image); we stamp 
# in the version and write to the home dir.
# ----------------------------------------------------------------------
section "Initializing Claude configuration in ~/.claude.json"

sed "s/__CLAUDE_CODE_VERSION__/${CLAUDE_CODE_VERSION}/" \
    /etc/claude-dev/.claude.json.template > "${HOME}/.claude.json"
chmod 600 "${HOME}/.claude.json"
echo "lastOnboardingVersion: ${CLAUDE_CODE_VERSION}"
mkdir -p "${HOME}/.claude"
success "Initialized ~/.claude.json."

# ======================================================================
# PROJECT — molim-specific dependency installation
# ======================================================================

# ----------------------------------------------------------------------
# Install Python and project dependencies via uv
# uv resolves Python from the project's .python-version /
# pyproject.toml, then installs locked deps from uv.lock.
# --frozen ensures no resolution against package registries.
# ----------------------------------------------------------------------
section "Installing project dependencies via uv sync"

uv sync --frozen
success "Project dependencies installed."

# ======================================================================
# COMMON — handoff to CMD
# ======================================================================

section "Bootstrap complete"

if [[ -n "${ISSUE_ID:-}" ]]; then
    ISSUE_TITLE="$(gh issue view "${ISSUE_ID}" --repo "${GH_OWNER}/${GH_REPO}" --json title --jq .title 2>/dev/null || echo '(unable to fetch)')"
    echo "Issue: #${ISSUE_ID} — ${ISSUE_TITLE}."
fi
echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
COMMITS_AHEAD="$(git rev-list --count origin/main..HEAD 2>/dev/null || echo 0)"
if [[ "${COMMITS_AHEAD}" -gt 0 ]]; then
    echo "Commits ahead of origin/main: ${COMMITS_AHEAD}."
fi
echo

# ----------------------------------------------------------------------
# Final steps:
# - define exit trap to report git status trail
# - exec CMD (claude by default) with args passed from the launcher
# - drop into interactive bash when CMD exits
# ----------------------------------------------------------------------

git_trail() {
    section "Git state on exit"
    git -C /workspace status || true
    if git -C /workspace rev-parse @{u} >/dev/null 2>&1; then
        git --no-pager -C /workspace log --oneline @{u}..HEAD
    else
        echo "(branch not yet pushed to remote)"
    fi
    read -r -s -n 1 -p $'\nPress any key to exit the container...' _
}

trap git_trail EXIT

# Run CMD (claude by default, or any override). Bootstrap stays strict, but
# command failures after bootstrap should leave the user in an interactive
# shell for inspection instead of terminating the container immediately.
cmd_status=0
"$@" || cmd_status=$?

if [[ "$cmd_status" -ne 0 ]]; then
    warning "Command exited with status ${cmd_status}; dropping into interactive shell."
else
    echo "Command exited successfully; dropping into interactive shell."
fi

bash
exit "$cmd_status"


# run CMD (claude by default, or any override)
"$@"
# drop into interactive bash when CMD exits
# when bash exits → trap fires → git trail → container exits
bash
