#!/bin/bash
# ======================================================================
# entrypoint.sh — Claude Code dev environment bootstrap
#
# Runs as the container's ENTRYPOINT. Receives configuration via env
# vars from the launcher (claude-dev.sh on the host):
#   GH_OWNER, GH_REPO            project identity
#   GH_TOKEN                     GitHub Token (read/write per scoping)
#   CLAUDE_CODE_OAUTH_TOKEN      consumed later by claude itself
#   TZ                           host timezone
#   ISSUE_ID                     optional GitHub Issue number
#   CLAUDE_DEV_PROXY_SOCKET      path to bind-mounted proxy socket
#   CLAUDE_DEV_PROXY_PORT        local port to expose the proxy via socat bridge
#
# Organized into two logical sections:
#   1. BASE — generic Claude Code dev environment bootstrap
#   2. PROJECT — molim-specific dependency installation
#
# Eventually the BASE section will be extracted into a separately-
# published base image's entrypoint; for now both live here.
#
# ======================================================================

set -euo pipefail

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------
section() {
    printf '\n\033[1;32m==> %s\033[0m\n' "$*"
}

die() {
    echo "\033[1;31mError:\033[0m $*" >&2
    exit 1
}

warning() {
    printf '\033[1;33mWarning:\033[0m %s\n' "$*" >&2
}

success() {
    printf '\033[1;32m✓\033[0m %s\n' "$*"
}

# ======================================================================
# BASE — generic Claude Code dev environment bootstrap
# ======================================================================
section "Welcome to ephemeral Claude Code dev environment"

# ----------------------------------------------------------------------
# Validate required environment
# ----------------------------------------------------------------------
section "Validating environment"

validation_failure() {
    printf '\n\033[1;31m==> %s\033[0m\n' "Entrypoint validation failed, Claude container cannot proceed."
    read -r -s -n 1 -p $'\nPress any key to exit the container...' _
}
trap validation_failure EXIT

require_env() {
    local var="$1"
    local show_value="${2:-false}"
    if [[ -z "${!var:-}" ]]; then
        die "required environment variable '${var}' is not set; check the launcher."
    fi
    local text="$var"
    if [[ "$show_value" == "true" ]]; then
        text="${text}=${!var}"
    fi
    success $text
}

require_env GH_OWNER true
require_env GH_REPO true
require_env GH_TOKEN
require_env CLAUDE_CODE_OAUTH_TOKEN
require_env TZ true
require_env CLAUDE_DEV_PROXY_SOCKET
require_env CLAUDE_DEV_PROXY_PORT

# ----------------------------------------------------------------------
# Issue ID handling
# ----------------------------------------------------------------------
if [[ -n "${ISSUE_ID:-}" ]]; then
    success "ISSUE_ID=${ISSUE_ID}"
else
    success "ISSUE_ID not set. No specific Issue context."
fi

# ----------------------------------------------------------------------
# Bash prompt configuration
# ----------------------------------------------------------------------
section "Configuring bash prompt"

configure_bash_prompt() {
    local context="${GH_REPO}"

    if [[ -n "${ISSUE_ID:-}" ]]; then
        context="${context} #${ISSUE_ID}"
    fi

    cat > "${HOME}/.bashrc" <<EOF
# Claude dev container prompt.
# Generated by entrypoint.sh.

export PS1='\\[\\033[1;36m\\][claude-dev ${context}]\\[\\033[0m\\] \\w\\$ '
EOF
}
configure_bash_prompt
success "Configured bash prompt."

# ----------------------------------------------------------------------
# Verify /workspace is empty
# A non-empty /workspace means the container deviates from design
# (a bind mount, a stale tmpfs, etc.); fail loudly rather than risk
# clobbering or merging unexpected content.
# ----------------------------------------------------------------------
section "Verifying /workspace is empty"

if [[ -n "$(ls -A /workspace 2>/dev/null)" ]]; then
    die "/workspace is not empty. Container is in an unexpected state; aborting."
fi
success "/workspace is clean."

# ----------------------------------------------------------------------
# Check container network mode - expected --network none
# No routes, only loopback interface.
# Show warning if this does not appear to be the case, but do not fail.
# ----------------------------------------------------------------------
section "Checking container network mode; --network none expected"

warn_if_not_network_none() {
    local interfaces=""
    local has_non_loopback=0
    local has_default_route=0

    # /sys/class/net is available without iproute2/net-tools.
    if [[ -d /sys/class/net ]]; then
        interfaces="$(basename -a /sys/class/net/* 2>/dev/null | sort | tr '\n' ' ')"

        while IFS= read -r iface; do
            if [[ "$iface" != "lo" ]]; then
                has_non_loopback=1
                break
            fi
        done < <(basename -a /sys/class/net/* 2>/dev/null)
    else
        warning "Cannot inspect /sys/class/net; unable to verify container network mode."
        return 0
    fi

    # /proc/net/route exposes kernel route table without requiring iproute2.
    # A default route has destination 00000000.
    if [[ -r /proc/net/route ]]; then
        if awk 'NR > 1 && $2 == "00000000" { found=1 } END { exit found ? 0 : 1 }' /proc/net/route; then
            has_default_route=1
        fi
    else
        warning "Cannot inspect /proc/net/route; unable to verify default route state."
    fi

    if [[ "$has_non_loopback" -eq 1 || "$has_default_route" -eq 1 ]]; then
        warning "Container does not appear to be running with Docker --network none."
        warning "Detected network interfaces: ${interfaces:-unknown}"
        if [[ "$has_default_route" -eq 1 ]]; then
            warning "Detected a default route in /proc/net/route."
        fi
        warning "Network isolation is expected to be enforced by the host launcher."
    else
        success "Network mode check successful: loopback-only network observed. Expected for --network none."
    fi
}
warn_if_not_network_none

# ----------------------------------------------------------------------
# Check container capability and privilege restrictions
# Expected: all capabilities dropped, no-new-privileges enabled.
# Show warning if this does not appear to be the case, but do not fail.
# ----------------------------------------------------------------------
section "Checking container capability and privilege restrictions; --cap-drop ALL and --security-opt no-new-privileges expected"

warn_if_not_hardened() {
    local cap_eff=""
    local no_new_privs=""

    if [[ ! -r /proc/self/status ]]; then
        warning "Cannot inspect /proc/self/status; unable to verify capability/no-new-privileges state."
        return 0
    fi

    cap_eff="$(awk '/^CapEff:/ {print $2}' /proc/self/status)"
    no_new_privs="$(awk '/^NoNewPrivs:/ {print $2}' /proc/self/status)"

    if [[ "$cap_eff" == "0000000000000000" ]]; then
        success "Capability check successful: no effective capabilities observed. Expected for --cap-drop ALL."
    else
        warning "Container effective capabilities are not fully dropped: CapEff=${cap_eff:-unknown}"
    fi

    if [[ "$no_new_privs" == "1" ]]; then
        success "Privilege check successful: no-new-privileges is enabled. Expected for --security-opt no-new-privileges."
    else
        warning "Container no-new-privileges is not enabled: NoNewPrivs=${no_new_privs:-unknown}"
    fi
}
warn_if_not_hardened

# ----------------------------------------------------------------------
# Local proxy configuration
# The real Envoy proxy is exposed on a bind-mounted socket at $CLAUDE_DEV_PROXY_SOCKET.
# socat is used as a bridge to connect to the proxy.
# ----------------------------------------------------------------------
section "Network proxy bridge initialization"

start_proxy_bridge() {
    local socket_path="${CLAUDE_DEV_PROXY_SOCKET}"
    local proxy_port="${CLAUDE_DEV_PROXY_PORT:-8080}"
    local proxy_url="http://127.0.0.1:${proxy_port}"
    local log_file="/tmp/claude-dev-proxy-socat.log"

    if [[ ! -S "${socket_path}" ]]; then
        die "Claude dev proxy socket not found or not a socket: ${socket_path}"
    fi

    : > "${log_file}"

    socat -d -d \
        "TCP-LISTEN:${proxy_port},bind=127.0.0.1,reuseaddr,fork" \
        "UNIX-CONNECT:${socket_path}" \
        2>"${log_file}" &

    local socat_pid="$!"

    # Wait until the local TCP listener is reachable.
    for _ in {1..50}; do
        if ! kill -0 "${socat_pid}" >/dev/null 2>&1; then
            cat "${log_file}" >&2 || true
            die "Network proxy bridge process exited before becoming ready."
        fi

        if timeout 1 bash -c ":</dev/tcp/127.0.0.1/${proxy_port}" >/dev/null 2>&1; then
            export HTTP_PROXY="${proxy_url}"
            export HTTPS_PROXY="${proxy_url}"
            export http_proxy="${proxy_url}"
            export https_proxy="${proxy_url}"
            export NO_PROXY="${NO_PROXY:-localhost,127.0.0.1,::1}"
            export no_proxy="${no_proxy:-localhost,127.0.0.1,::1}"

            echo "Proxy socket: ${socket_path}"
            echo "Proxy bridge: ${proxy_url}"
            echo "socat log: ${log_file}"
            success "Network proxy bridge started."
            return 0
        fi

        sleep 0.1
    done

    cat "${log_file}" >&2 || true
    die "Network proxy bridge did not become ready on 127.0.0.1:${proxy_port}"
}
start_proxy_bridge

# ----------------------------------------------------------------------
# Configure GitHub authentication via gh
# This installs gh's git credential helper as a side effect, so both
# `gh` and `git` work against github.com without further setup.
# ----------------------------------------------------------------------
section "Configuring GitHub authentication"

GH_TOKEN_TMP="$GH_TOKEN"
unset GH_TOKEN
echo "$GH_TOKEN_TMP" | gh auth login --with-token --hostname github.com
unset GH_TOKEN_TMP
gh auth setup-git
gh auth status
success "GitHub authentication initialized."

# ----------------------------------------------------------------------
# Configure git identity
# Author is "Claude Code (authorized by <gh-user>)", email uses GitHub's
# noreply format keyed by the human's numeric user ID so the avatar
# routes to the human's profile.
# ----------------------------------------------------------------------
section "Configuring git identity"

GH_USER_ID="$(gh api user --jq .id)"
GH_USERNAME="$(gh api user --jq .login)"
GIT_AUTHOR_NAME="Claude Code (authorized by ${GH_USERNAME})"
GIT_AUTHOR_EMAIL="${GH_USER_ID}+${GH_USERNAME}@users.noreply.github.com"
git config --global user.name  "${GIT_AUTHOR_NAME}"
git config --global user.email "${GIT_AUTHOR_EMAIL}"
success "Author: ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>."

# ----------------------------------------------------------------------
# Clone the project repository
# ----------------------------------------------------------------------
section "Cloning ${GH_OWNER}/${GH_REPO} into /workspace"

git clone "https://github.com/${GH_OWNER}/${GH_REPO}.git" /workspace
cd /workspace
success "Repository cloned."

# ----------------------------------------------------------------------
# Resolve and check out the working branch
#
#   ISSUE_ID not set                       -> stay on main
#   ISSUE_ID set, issue does not exist     -> error
#   ISSUE_ID set, issue exists, 0 branches -> stay on main
#   ISSUE_ID set, issue exists, 1 branch   -> check it out
#   ISSUE_ID set, issue exists, ≥2 branches -> refuse and exit
#
# Implemented via GraphQL because `gh issue develop --list` does not
# support --json output. The first:2 cap is sufficient since logic
# only distinguishes 0 / 1 / multiple.
# ----------------------------------------------------------------------
section "Resolving working branch"

resolve_working_branch() {
    if [[ -z "${ISSUE_ID:-}" ]]; then
        success "No ISSUE_ID; staying on main."
    else

        if ! gh issue view "${ISSUE_ID}" --repo "${GH_OWNER}/${GH_REPO}" --json number >/dev/null 2>&1; then
            die "Issue #${ISSUE_ID} not found in ${GH_OWNER}/${GH_REPO}."
        fi

        QUERY_RESULT="$(gh api graphql \
            -F owner="${GH_OWNER}" \
            -F repo="${GH_REPO}" \
            -F number="${ISSUE_ID}" \
            -f query='
                query($owner: String!, $repo: String!, $number: Int!) {
                repository(owner: $owner, name: $repo) {
                    issue(number: $number) {
                    linkedBranches(first: 2) {
                        nodes { ref { name } }
                    }
                    }
                }
                }')"

        # Issue not found -> .data.repository.issue is null
        if [[ "$(echo "${QUERY_RESULT}" | jq '.data.repository.issue')" == "null" ]]; then
            die "Issue #${ISSUE_ID} not returned by GraphQL API in ${GH_OWNER}/${GH_REPO}."
        fi

        LINKED_BRANCHES="$(echo "${QUERY_RESULT}" | jq -r '.data.repository.issue.linkedBranches.nodes | map(.ref.name)')"
        LINKED_COUNT="$(echo "${LINKED_BRANCHES}" | jq 'length')"

        case "${LINKED_COUNT}" in
            0)
                success "Issue #${ISSUE_ID}: no linked branch yet; staying on main."
                echo "Branch creation is the SDLC's spec phase responsibility."
                ;;
            1)
                BRANCH="$(echo "${LINKED_BRANCHES}" | jq -r '.[0]')"
                echo "Issue #${ISSUE_ID}: one linked branch (${BRANCH}); checking out."
                git checkout "${BRANCH}"
                success "Checked out linked branch ${BRANCH} for Issue #${ISSUE_ID}."
                ;;
            *)
                echo "Issue #${ISSUE_ID}: multiple linked branches found:" >&2
                echo "${LINKED_BRANCHES}" | jq -r '.[]' | sed 's/^/  - /' >&2
                die "Ambiguous branch state. Resolve in GitHub (Issue page → Development sidebar → unlink unwanted branches) and retry."
                ;;
        esac
    fi
}
resolve_working_branch

# ----------------------------------------------------------------------
# Write ~/.claude.json
# Suppresses the first-run onboarding wizard (theme picker, login method
# screen). hasCompletedOnboarding is the gate; lastOnboardingVersion
# must match the installed Claude Code version. Template lives at
# /etc/claude-dev/.claude.json.template (baked into the image); we stamp 
# in the version and write to the home dir.
# ----------------------------------------------------------------------
section "Initializing CLaude configuration in ~/.claude.json"

sed "s/__CLAUDE_CODE_VERSION__/${CLAUDE_CODE_VERSION}/" \
    /etc/claude-dev/.claude.json.template > "${HOME}/.claude.json"
chmod 600 "${HOME}/.claude.json"
echo "lastOnboardingVersion: ${CLAUDE_CODE_VERSION}"
success "Initialized ~/.claude.json."

# ======================================================================
# PROJECT — molim-specific dependency installation
# ======================================================================

# ----------------------------------------------------------------------
# Install Python and project dependencies via uv
# uv resolves Python from the project's .python-version /
# pyproject.toml, then installs locked deps from uv.lock.
# --frozen ensures no resolution against package registries.
# ----------------------------------------------------------------------
section "Installing project dependencies via uv sync"

uv sync --frozen
success "Project dependencies installed."

# ======================================================================
# COMMON — handoff to CMD
# ======================================================================

section "Bootstrap complete"

if [[ -n "${ISSUE_ID:-}" ]]; then
    ISSUE_TITLE="$(gh issue view "${ISSUE_ID}" --repo "${GH_OWNER}/${GH_REPO}" --json title --jq .title 2>/dev/null || echo '(unable to fetch)')"
    echo "Issue: #${ISSUE_ID} — ${ISSUE_TITLE}."
fi
echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
COMMITS_AHEAD="$(git rev-list --count origin/main..HEAD 2>/dev/null || echo 0)"
if [[ "${COMMITS_AHEAD}" -gt 0 ]]; then
    echo "Commits ahead of origin/main: ${COMMITS_AHEAD}."
fi
echo

# ----------------------------------------------------------------------
# Final steps:
# - define exit trap to report git status trail
# - exec CMD (claude by default) with args passed from the launcher
# - drop into interactive bash when CMD exits
# ----------------------------------------------------------------------

git_trail() {
    section "Git state on exit"
    git -C /workspace status
    if git -C /workspace rev-parse @{u} >/dev/null 2>&1; then
        git --no-pager -C /workspace log --oneline @{u}..HEAD
    else
        echo "(branch not yet pushed to remote)"
    fi
    read -r -s -n 1 -p $'\nPress any key to exit the container...' _
}

trap git_trail EXIT

# run CMD (claude by default, or any override)
"$@"
# drop into interactive bash when CMD exits
# when bash exits → trap fires → git trail → container exits
bash    
