name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python
        run: uv python install

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Install and cache CLI tools
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: rawtherapee imagemagick ffmpeg
          version: 1.0

      - name: Run tests
        run: uv run pytest
